apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: product-mgt
  name: product-mgt
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: product-mgt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-mgt
    spec:
      containers:
        - image: thathsara99/products-2022-ctse
          imagePullPolicy: Always
          name: products-2022-ctse
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

1/1     Running
